services:
  postgres:
    image: postgres:16
    container_name: bptech_postgres_db
    environment:
      TZ: 'America/Sao_Paulo'
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - .tmp/database:/var/lib/postgresql/data

  backend:
    container_name: bptech_postgres_app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - PORT=${APP_PORT}
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
